# ---------------------------------------------------------------------------
# Module manifest for module 'nuke'
#
# Generated on: 2022-06-14
# Generated by: eggheadedmonkey <cyko@eggheadedmonkey.com>
# ---------------------------------------------------------------------------

@{

  # fake/dry-run (don't do anything, just print)
  test = $false
  # ignored files (ie. don't delete)
  keep = @(
    ".gitkeep"
  )

}
