# ---------------------------------------------------------------------------
# nuke configuration (module manifest)
#
# Generated on: 2022-06-14
# Generated by: cykomaniacs / eggheadedmonkey <cyko@eggheadedmonkey.com>
# ---------------------------------------------------------------------------

@{
  #--------------------------------------------------------------------------
  #region standard parameters
  #--------------------------

  ModuleVersion = '1.1.0'
  GUID = 'aa58b76b-1c0c-48a8-a999-64b67740905a' # UID of this module
  Author = 'eggheadedmonkey <cyko@eggheadedmonkey.com>'
  CompanyName = 'cykomaniacs'
  Copyright = 'cykomaniacs 2022' # "(c) cykomaniacs 2022"
  Description = 'Generic build cleaner for Windows'

  #---------
  #endregion
  #--------------------------------------------------------------------------

  # information (about, authors, version, etc...)
  info = @{
    description = "Generic build cleaner for Windows"
    summary = "build cleaner"
    # --------------------------------
    # .number: major.minor.patch
    #   .name: codename
    # --------------------------------
    version = @{ number = "0.1.2"; name = "configurizer" }
    # --------------------------------
    # .name: ...
    # .home: web url
    # .mail: contact email
    # --------------------------------
    author = @{
      name = "eggheadedmonkey"
      home = "https://github.com/eggheadedmonkey"
      mail = "cyko@eggheadedmonkey.com"
    }
    # --------------------------------
    # .name: ...
    # .home: web url
    # .mail: contact email
    # --------------------------------
    organization = @{
      name = "cykomaniacs"
      home = "https://github.com/cykomaniacs"
      mail = "cyko@eggheadedmonkey.com"
    }
  }
  # timestamps
  date = @{
    created = "2022/06/14"
    updated = "2022/06/15"
  }
  # repository url
  repo = "https://github.com/cykomaniacs/cyko"
  # dry-run (don't do anything, just print)
  fake = $false
  # ignored files (ie. don't delete)
  keep = @(
    ".gitkeep"
  )

}
