# ---------------------------------------------------------------------------
# Module manifest for module 'nuke'
#
# Generated by: eggheadedmonkey
# Generated on: 2022-06-14
# ---------------------------------------------------------------------------

@{

  # ignored files (ie. don't delete)
  keep = @(
    ".gitkeep", "cyko.exe"
  )

  testv = "fdffdf"
}
